web/router.ex
defmodule Hansard.Router do
  use Hansard.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Hansard do
    pipe_through :browser # Use the default browser stack

    # get "/", PageController, :index
    resources "/", SpeechController
  end

  scope "/auth", Hansard do
    pipe_through :browser

    get "/:provider", AuthController, :index
    get "/:provider/callback", AuthController, :callback
  end
  # Other scopes may use custom stacks.
  # scope "/api", Hansard do
  #   pipe_through :api
  # end
end

lib/hansard/endpoint.ex
defmodule Hansard.Endpoint do
  use Phoenix.Endpoint, otp_app: :hansard

  socket "/socket", Hansard.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :hansard, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_hansard_key",
    signing_salt: "u9VKp5vE"

  plug Hansard.Router
end

lib/hansard/repo.ex
defmodule Hansard.Repo do
  use Ecto.Repo, otp_app: :hansard
end

web/models/speech.ex
defmodule Hansard.Speech do
  use Hansard.Web, :model

  schema "speeches" do
    field :speaker, :string
    field :description, :string
    field :class_year, :integer

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:speaker, :description, :class_year])
    |> validate_required([:speaker, :description, :class_year])
  end
end

web/controllers/auth_controller.ex
defmodule Hansard.AuthController do
  use Hansard.Web, :controller

  def index(conn, %{"provider" => provider}) do
    redirect conn, external: authorize_url!(provider)
  end

  def callback(conn, %{"provider" => provider, "code" => code}) do
    #IO.puts "Connection is: #{conn}"
    IO.puts "Provider is: #{provider}"
    IO.puts "Code is: #{code}"
    token = get_token!(provider, code)
    user = get_user!(provider, token)

    IO.puts "Finished get_token and get_user"
    conn
    |> put_session(:current_user, user)
    |> put_session(:access_token, token.access_token)
    |> redirect(to: "/")
  end

  defp authorize_url!("google") do
    Google.authorize_url!(scope: "email profile")
  end

  defp authorize_url!(_) do
    raise "No matching provider available."
  end

  defp get_token!("google", code) do
    Google.get_token!(code: code)
  end

  defp get_token!(_, _) do
    raise "No matching provider available."
  end

  defp get_user!("google", token) do
    user_url = "https://www.googleapis.com/plus/v1/people/me/openIdConnect"
    OAuth2.AccessToken.get!(token, user_url)
  end
end

web/controllers/page_controller.ex
defmodule Hansard.PageController do
  use Hansard.Web, :controller

  def index(conn, _params) do
    conn
    |> assign(:current_user, get_session(conn, :current_user))
    |> render("index.html")
  end
end

web/controllers/speech_controller.ex
defmodule Hansard.SpeechController do
  use Hansard.Web, :controller

  alias Hansard.Speech

  def index(conn, _params) do
    speeches = Enum.reverse(Repo.all(Speech))
    changeset = Speech.changeset(%Speech{})
    render(conn, "index.html", speeches: speeches, changeset: changeset)
  end

  def new(conn, _params) do
    changeset = Speech.changeset(%Speech{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"speech" => speech_params}) do
    changeset = Speech.changeset(%Speech{}, speech_params)

    case Repo.insert(changeset) do
      {:ok, speech} ->
        # Send speech to all currently connected clients.
        Hansard.SpeechChannel.broadcast_change(speech)
        # Remove Redirect.
        conn
        |> put_flash(:info, "Speech created successfully.")
        |> redirect(to: speech_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    speech = Repo.get!(Speech, id)
    render(conn, "show.html", speech: speech)
  end

  def edit(conn, %{"id" => id}) do
    speech = Repo.get!(Speech, id)
    changeset = Speech.changeset(speech)
    render(conn, "edit.html", speech: speech, changeset: changeset)
  end

  def update(conn, %{"id" => id, "speech" => speech_params}) do
    speech = Repo.get!(Speech, id)
    changeset = Speech.changeset(speech, speech_params)

    case Repo.update(changeset) do
      {:ok, speech} ->
        conn
        |> put_flash(:info, "Speech updated successfully.")
        |> redirect(to: speech_path(conn, :show, speech))
      {:error, changeset} ->
        render(conn, "edit.html", speech: speech, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    speech = Repo.get!(Speech, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(speech)

    conn
    |> put_flash(:info, "Speech deleted successfully.")
    |> redirect(to: speech_path(conn, :index))
  end
end

web/views/error_view.ex
defmodule Hansard.ErrorView do
  use Hansard.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Hansard.LayoutView do
  use Hansard.Web, :view
end

web/views/page_view.ex
defmodule Hansard.PageView do
  use Hansard.Web, :view
end

web/views/speech_view.ex
defmodule Hansard.SpeechView do
  use Hansard.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Hansard!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav class="navbar navbar-default">
          <h2>HANSARD</h2>
        </nav>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <%= if @current_user do %>
    <h2>Welcome, <%= @current_user["name"] %>!</h2>
  <% else %>
    <%= link to: auth_path(@conn, :index, "google"), class: "btn btn-primary" do %>
      Sign in with Google
    <%= end %>
  <% end %>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul id="show-list">
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/speech/edit.html.eex
<h2>Edit speech</h2>

<%= render "form.html", changeset: @changeset,
                        action: speech_path(@conn, :update, @speech) %>

<%= link "Back", to: speech_path(@conn, :index) %>

web/templates/speech/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :speaker, class: "control-label" %>
    <%= text_input f, :speaker, class: "form-control" %>
    <%= error_tag f, :speaker %>
  </div>

  <div class="form-group">
    <%= label f, :class_year, class: "control-label" %>
    <%= number_input f, :class_year, class: "form-control" %>
    <%= error_tag f, :class_year %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/speech/index.html.eex
<h2>Listing speeches</h2>
<table class="table">
  <thead>
    <tr>
      <th>Speaker</th>
      <th>Class year</th>
      <th>Spoken at</th>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody id="show-list" data-id="lobby">
<%= for speech <- @speeches do %>
    <tr>
      <td><%= speech.speaker %></td>
      <td><%= speech.class_year %></td>
      <td><%= speech.inserted_at %></td>
      <td><%= speech.description %></td>

      <td class="text-right">
        <%= link "Show", to: speech_path(@conn, :show, speech), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: speech_path(@conn, :edit, speech), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: speech_path(@conn, :delete, speech), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New speech", to: speech_path(@conn, :new) %>

web/templates/speech/new.html.eex
<h2>New speech</h2>

<h2>Create a new speech</h2>
<%= render "form.html", changeset: @changeset,
                        action: speech_path(@conn, :create) %>

<%= link "Back", to: speech_path(@conn, :index) %>

web/templates/speech/show.html.eex
<h2>Show speech</h2>

<ul>

  <li>
    <strong>Speaker:</strong>
    <%= @speech.speaker %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @speech.description %>
  </li>

  <li>
    <strong>Class year:</strong>
    <%= @speech.class_year %>
  </li>

</ul>

<%= link "Edit", to: speech_path(@conn, :edit, @speech) %>
<%= link "Back", to: speech_path(@conn, :index) %>